name: Update external data

on:
  schedule:
    - cron: '0 3 * * 0' 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Télécharger le fichier si le cache est manquant
        run: |
          FILE_URL="https://lorcanajson.org/files/current/fr/allCards.json"
          DEST="src/allCards.json"
          curl -fSL "$FILE_URL" -o "$DEST"

      - name: Vérifier le fichier
        run: |
          if [[ ! -s src/allCards.json ]]; then
            echo "❌ Fichier vide ou manquant"
            exit 1
          fi

      - name: Commit du fichier mis à jour
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/allCards.json
          git diff --cached --quiet || git commit -m "Update external data.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
